package com.order.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.order.repositories.converters.LocalDateTimeConverter;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "Orders")
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class OrderDocument {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private double price;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime creationDate;
    @DynamoDBAttribute
    private CustomerDocument customer;
    @DynamoDBAttribute
    private List<ProductDocument> products;

    public double getPrice() {
        if (!this.products.isEmpty() && price == 0) {
            calculatePrice();
        }

        return this.price;
    }

    private void calculatePrice() {
        this.price = this.products.stream()
                .mapToDouble(o -> o.getPrice() * o.getAmount())
                .sum();
    }
}
